### ISSUE TITLE
Possible problem with use of Gauss Hermite quadrature

### ISSUE THREAD

**Issue by jagman88** [EconForge/dolo#108]
While playing around with a model file, I got to using the Gauss-Hermite quadrature function `gauss_hermite_nodes` in `quadrature.py`. This function is called when using `discretize` on a model distribution object, e.g.

```
distrib = model.get_distribution()
nodes, weights = distrib.discretize()
```

However, I noticed that while the Gauss-Hermite function takes the standard deviation of a function*, the convention we use for writing the distribution section of a dtcscc model file is to use the variance, e.g. 

```
options:
    distribution: !Normal
        sigma: [ [ sig_e**2] ]
```

So writing our yaml files in the standard way seems to lead to incorrect use of the quadrature routine. Any suggestions for how to make sure that the yaml file convention and the quadrature function use are consistent? 

*(I'm pretty sure this is the case. There's no documentation for the function in the  `quadrature.py` file, but it seems to be written as it's described on the [wiki page](https://en.wikipedia.org/wiki/Gauss%E2%80%93Hermite_quadrature) which uses the standard deviation rather than the variance).

**Comment by albop** [comment]
Thanks @jagman88, this is a serious one. From looking at the code, I guess, it looks like line 78 in `quadrature.py` should be `x = numpy.array(points)*numpy.sqrt(sigma)` instead of x = numpy.array(points)*sigma`.
It would seem that the multivariate case (with the cholesky factorization) is not affected.  Could you confirm it ?

**Comment by albop** [comment]
Btw, I didn't respond to your question about how to make the api consistent. For multivariate processes, it doesn't make too much sense to use standard deviations, so that the default, is to use supply the covariance matrix.
I guess, for 1d shocks (and in the yaml file), we could add an option to supply stdev instead. We could have:
```

**Comment by jagman88** [comment]
No problem, @albop. Yes, I think if we make your initial fix, that will cover the one dimensional case. That would also mean the yaml file and quadrature routines are consistent, so we wouldn't need to make the edit in your second comment.

I think that you are right that the multivariate case is not affected. To compute the quadrature nodes, the common component across univariate and multivariate cases is the use of Hermite polynomials, which don't use the variance as an input. The variances are used when computing the nodes, but the multivariate case explicitly uses the variance-covariance matrix, so there is no inconsistency between what's defined in the yaml file and the computation of the nodes.

I'll make the small fix noted above and add some quick documentation so that it's clear what's going on.
