### ISSUE TITLE
Solution accuracy in rbc_model.ipynb

### ISSUE THREAD

**Issue by yaniv256** [EconForge/dolo#63]
Hi Pablo,

I was going over `rbc_model.ipynb`, working on some edits and there are two results there that seem strange:
- The chart in Out[24] on the [original](http://nbviewer.ipython.org/github/yaniv256/dolo/blob/c776ac3930829e359b703048f594268caade8d09/examples/notebooks/rbc_model.ipynb) and Out[20] on the [recomputed](http://nbviewer.ipython.org/github/yaniv256/dolo/blob/1ff382b0be9c4c7dd9ef3068c678cbf6c270005c/examples/notebooks/rbc_model.ipynb) notebook shows a non constant distribution over time. This is strange because the simulation is started from the deterministic steady state. I know that the deterministic steady state is not exactly on the mean of the ergodic distribution but the difference for RBC should be negligible. 
- The errors for time iteration in Out[35] on the original and Out[27] on the recomputed seem too large.

**Comment by albop** [comment]
Thank you for these excellent reamarks.
There is indeed a mistake in the notebook: in the sensitivity analysis part, there are a couple of `model.set_calibration(delta=val)` calls. These ones modify the calibration in place, so that after the last call, the model calibration doesn't much the one used for the global solution stored in `dr_global`. This can explain both the accuracy errors and the strange pattern in the stochastic simulations. I'll fix that soon.
The behaviour of `set_calibration` seems to confuse a few users (including me). May be one good idea would be to add a `new_calibration()` command with the same syntax that would return a new model without shared references.

**Comment by yaniv256** [comment]
Awesome! [Now](http://nbviewer.ipython.org/github/yaniv256/dolo/blob/26b3cc0d388c094dc25632ddf8c4cfd095df4fb9/examples/notebooks/rbc_model.ipynb) it looks much better. I did not know perturbation does this bad on labour. Are you sure this is a valid result?

**Comment by albop** [comment]
Well, here good or bad is a matter of personal appreciation. To me, it produces very similary dynamics. When looking at the Eueler equations, the errors from the first order perturbations, have a constant bias that disappear from the second-order perturbations, mostly due to correction in the constant term. If you do `dr=approximate_controls(model, order=2)` instead, the approximation should be fairly good.
Btw, I see that you have fixed the former problem in the notebook. Can I incorporate your modifications ?

**Comment by yaniv256** [comment]
Oh, thats right. I'll switch the notebook to second order perturbation. First order is not appropriate because it create a false impression of superiority for the global solution.
