### ISSUE TITLE
slycot dependecy

### ISSUE THREAD

**Issue by yaniv256** [EconForge/dolo#65]
We should probably either fetch it on dolo install or generate our own exception with slycot install instructions.

**Comment by albop** [comment]
Yes, the problem used to be that Slycot was not easy to install on all platform. The situation has a bit improved after it was forked, since it is now pip-installable.
I have no idea whether it is pip-installable on windows though. Which platform are you using ?

**Comment by yaniv256** [comment]
I'm on Ubuntu. By the way, Slycot pip installed for pip2 but failed for pip3. I was actually a bit amazed that all that fortran actually complied. I think it may be a bit smarter to issue a sensible exception when we need it plus a notice on the install page rather then pull it in on install. Install for me was a [pain](https://github.com/numba/llvmlite/issues/27) as it is due to the Nubma dependency. I mean, the typical user should be an academic economist which cannot be expected to know how to `apt-get llvm-3.5-dev` from an upstream repository, nor understand what is JIT compiling. Ideally, and I am not saying this is a high priority at this point, but ideally, hard-to-install stuff like Numba and Slycot should be optional, and users should get to see dolo in action before they are asked to go through installing it.

**Comment by albop** [comment]
As for Slycot I completely agree. It is part of the optional dependencies and I agree that error messages should be more helpful.
I'm not sure that numba should be regarded as a difficult dependency though : to me, it is part of the scientific stack and is distributed with all scientific python distributions (especially anaconda). Lately, I have tended to favour it rather than Cython, mainly for portability reasons (numba makes dolo a source only package). Without it, several parts would be way to slow. 
When dealing with typical with typical academic economists, it just seems easier to assume that they can install anaconda python. For linux users, it works very well in user-space. Any reason, you don't want to use it ?

**Comment by yaniv256** [comment]
You are right. Anaconda makes this very easy for that case. So strike my rant please. I have some reasons why I prefer system Python, but I am not sure they are good ones. If conda was better documented for the system wide install case I would probably not mind it at all. As it was I believe the last straw was that some packages kept getting installed into system python even though I was using the Anaconda pip.

**Comment by albop** [comment]
@yaniv256, I'm reopening this one:
- we are not providing a good error message when Slycot is not found (when you do `approximate_controls(model, order=2)` without it
- I'd like to make some tests to see if the situation on python 3 can be improved or not
Let's wait a bit before putting a `wontfix` flag on it.

**Comment by albop** [comment]
Slycot is now installable via conda or pip with Python 3
